tool_name: Devin
format: command_based
tone: balanced_technical
framework: Autonomous software engineering
preferred_use_cases:
- web_development
- code_generation
- debugging
- testing
- api_integration
prompting_strategies:
  step_by_step:
    template: 'Step 1: {analysis} Step 2: {implementation} Step 3: {validation}'
    use_cases:
    - complex_tasks
    - debugging
    effectiveness_score: 0.9
  tool_based:
    template: Use {tool_name} to {action} for {objective}
    use_cases:
    - automated_tasks
    - integrations
    effectiveness_score: 0.85
  context_aware:
    template: 'Given context: {context}, implement {requirement} ensuring {constraints}'
    use_cases:
    - contextual_development
    - adaptive_solutions
    effectiveness_score: 0.8
development_stages:
- planning
- implementation
- testing
- deployment
- maintenance
supported_components:
- full_applications
- microservices
- apis
- databases
capabilities:
- still use coordinates as a fallback
- attachments which will generate public attachment URLs that you can use elsewhere
  too
- then use these secrets as ENV vars in your commands
- also use this command open and view
- here should start immediately after the closing angle bracket of the <insert
- leave this empty if you just want to press enter
- use elsewhere too
- the strings to find and replace within <old_str> and <new_str> tags inside the <str_replace
- freely highlight observations you see in your context
- also describe conditions for locations where no change should occur
constraints:
- available while in mode "planning"
- access any local backends but use public backend URLs
- spaces or tabs
- use the editor commands to create
- have a currently running shell process or unviewed content from a previous shell
  process
- remove part of a line
- works for FastAPI projects that use Poetry
- be shy
documentation_sources:
- data/devin_docs/comprehensive_system_prompt.md
extracted_metadata:
  source: comprehensive_ai_tools_repository
  files_processed: 1
  has_tools_config: false
